version: '3'

services:
  database:
    image: 'postgres:14'
    ports:
      - 5432:5432

    environment:
      POSTGRES_DB: blog_new_base
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
